namespace Domain.BackgroundJobs;

public record BackgroundJobDto(
    Guid Id,
    uint Attempts,
    string? Error,
    uint MaxRetries,
    string Payload,
    BackgroundJobPriority Priority,
    DateTimeOffset ScheduledFor,
    Guid? SourceId,
    BackgroundJobStatus Status,
    string? TraceId,
    BackgroundJobType Type,
    DateTimeOffset CreatedAt,
    DateTimeOffset? UpdatedAt,
    string? ConcurrencyStamp = null);

public record InternalBackgroundJobDto(
    long InternalId,
    Guid Id,
    uint Attempts,
    string? Error,
    uint MaxRetries,
    string Payload,
    BackgroundJobPriority Priority,
    DateTimeOffset ScheduledFor,
    Guid? SourceId,
    BackgroundJobStatus Status,
    string? TraceId,
    BackgroundJobType Type,
    DateTimeOffset CreatedAt,
    DateTimeOffset? UpdatedAt,
    string? ConcurrencyStamp = null) : BackgroundJobDto(
        Id,
        Attempts, 
        Error,
        MaxRetries, 
        Payload,
        Priority,
        ScheduledFor,
        SourceId,
        Status,
        TraceId,
        Type,
        CreatedAt,
        UpdatedAt,
        ConcurrencyStamp), IHasInternalCursor;